### ISSUE TITLE
Název a účel pluginu

### ISSUE THREAD

**Issue by Werkov** [fykosak/dokuwiki-plugin-fksvlna#1]
Název odpovídá tomu, že by plugin měl něco [kontrolovat](https://en.wikipedia.org/wiki/Lint_%28software%29), ale dle zdrojáků koukám, že jde o tu vlnu. Navrhuji přejmenování, třeba *-fksvlna apod., dokud to není mockrát referencováno.

**Comment by Werkov** [comment]
Cc: @cevro (přišla ti ta první notifikace anebo až teď, když Tě zmiňuji?)

**Comment by cevro** [comment]
prišla aj ta prvá.
Premenované.
